name: Run Python Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run bot
      env:
        TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      run: |
        python bot.py