name: Run Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-dejavu
    - name: Run bot
      env:
        API_KEY: ${{ secrets.API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        USER_ID: ${{ secrets.USER_ID }}
      run: python bot.py